spring.application.name=order-system

spring.datasource.url= jdbc:postgresql://localhost:5433/orxe
spring.datasource.username=postgres
spring.datasource.password=martin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true